"""add prescription_url to visits

Revision ID: c0e5d7506884
Revises: 689f53bca871
Create Date: 2026-05-11 14:42:40.106182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e5d7506884'
down_revision: Union[str, Sequence[str], None] = '689f53bca871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('prescription_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'prescription_url')
    # ### end Alembic commands ###
